### ISSUE TITLE
Pythonista 3

### ISSUE THREAD

**Issue by mncfre** [mevdschee/pythonista-minesweeper#1]
Hi, I love the game and how you implement it, but it don't work with pythonista 3, is it possible to make a version that run with pythonista 3 without using the 2.7 compiler?

**Comment by mncfre** [comment]
I modify your code in order to run the game with pythone 3, it works in my iphone 6, I run it in landscape with more bombs and columns, sorry for the customization.
[Mines3.txt](https://github.com/mevdschee/pythonista-minesweeper/files/316491/Mines3.txt)

**Comment by mevdschee** [comment]
Thank you! I added it.
